// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"pets-server/cmd/server/providers"
)

// Injectors from wire.go:

// InitializeApp 使用 Wire 初始化应用
// 这个函数的实现由 Wire 工具自动生成
func InitializeApp() (*App, func(), error) {
	config, err := providers.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := providers.ProvideDB(config)
	if err != nil {
		return nil, nil, err
	}
	repoSet := providers.ProvideRepoSet(db)
	speciesConfig, err := providers.ProvideSpeciesConfig()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	interpreterFactory := providers.ProvideInterpreterFactory()
	speciesRegistry, err := providers.ProvideSpeciesRegistry(speciesConfig, interpreterFactory)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	speciesFusionRegistry := providers.ProvideFusionRegistry(speciesConfig)
	unitOfWork := providers.ProvideUnitOfWork(db)
	client, cleanup2, err := providers.ProvideRedis(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cacheService := providers.ProvideCacheService(client)
	rankingStore := providers.ProvideRankingStore(client)
	sessionStore := providers.ProvideAuthSessionStore(client)
	authService := providers.ProvideWechatAuth(config)
	eventPublisher, cleanup3, err := providers.ProvideEventPublisher(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serviceSet := providers.ProvideServiceSet(config, repoSet, speciesRegistry, speciesFusionRegistry, unitOfWork, cacheService, rankingStore, sessionStore, authService, eventPublisher)
	hub := providers.ProvideWSHub()
	handler := providers.ProvideWSHandler(hub)
	engine := providers.ProvideRouter(config, serviceSet, handler, sessionStore)
	scheduler := providers.ProvideScheduler(repoSet, unitOfWork)
	app := NewApp(config, engine, hub, scheduler)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
